image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay
  SPRING_PROFILES_ACTIVE: gitlab-ci
  DOCKER_REPO : sb-works

stages:
  - build
  - push

maven-build:
  image: maven:3-jdk-8
  stage: build
  script:
    - "mvn clean install"
  artifacts:
    paths:
      - target/*.jar

docker-build:
  stage: push
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
  except:
    - master

docker-build-master:
  stage: push
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build --pull -t $CI_REGISTRY_IMAGE:master .
    - docker tag $CI_REGISTRY_IMAGE:master $CI_REGISTRY_USER/$DOCKER_REPO:master
    - docker push $CI_REGISTRY_USER/$DOCKER_REPO:master
  only:
    - master